[package]
name = "guest_management"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "guest_management"
path = "main.rs"

[dependencies]
chrono = { version = "0.4", features = ["clock"] }
env_logger = "0.11"
tokio = { version = "1.0", features = ["full"] }
unifi-client = { path = "../.." }
