edition = "2021"

# Widths
chain_width = 100
comment_width = 100
fn_call_width = 100
max_width = 100
single_line_if_else_max_width = 100

group_imports = "StdExternalCrate"
wrap_comments = true
format_code_in_doc_comments = true
imports_granularity = "Module"